export const initialFormState = {
  id: crypto.randomUUID(),
  name: "",
  alignment: "",
  books: [],
  strength: "",
  dexterity: "",
  constitution: "",
  intelligence: "",
  wisdom: "",
  charisma: "",
  class: "",
  race: "",
  level: 1,
}
